trigger_handle_names = {	...
	'AttenFixCtrl', ...
	'AttenFixValueCtrl', ...
	'AttenFixValueCtrlText', ...
	'AttenStepCtrl', ...
	'DAscaleCtrl', ...
	'FmaxCtrl', ...
	'FminCtrl', ...
	'FreqListCtrl', ...
	'FreqValText', ...
	'FstepCtrl', ...
	'ISICtrl', ...
	'MinLevelUnits', ...
	'MinlevelCtrl', ...
	'NrepsCtrl', ...
	'SideCtrl', ...
	'CollectBackgroundCtrl', ...
};


trigger_handles = [	...
	handles.AttenFixCtrl, ...
	handles.AttenFixValueCtrl, ...
	handles.AttenFixValueCtrlText, ...
	handles.AttenStepCtrl, ...
	handles.DAscaleCtrl, ...
	handles.FmaxCtrl, ...
	handles.FminCtrl, ...
	handles.FreqListCtrl, ...
	handles.FreqValText, ...
	handles.FstepCtrl, ...
	handles.ISICtrl, ...
	handles.MinLevelUnits, ...
	handles.MinlevelCtrl, ...
	handles.NrepsCtrl, ...
	handles.SideCtrl, ...
	handles.CollectBackgroundCtrl, ...
];